INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Aguascalientes');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Baja California');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Baja California Sur');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Campeche');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Coahuila de Zaragoza');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Colima');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Chiapas');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Chihuahua');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Ciudad de México');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Durango');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Guanajuato');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Guerrero');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Hidalgo');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Jalisco');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'México');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Michoacán de Ocampo');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Morelos');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Nayarit');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Nuevo León');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Oaxaca');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Puebla');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Querétaro');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Quintana Roo');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'San Luis Potosí');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Sinaloa');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Sonora');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Tabasco');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Tamaulipas');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Tlaxcala');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Veracruz de Ignacio de la Llave');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Yucatán');
INSERT INTO fosiles.estados (id_estado, nombre) VALUES (1, 'Zacatecas');