--CORE
CREATE TABLE FOSILES.FOSILES (
    ID_FOSIL NUMBER,
    MUESTRA VARCHAR2(10),
    GRUPO VARCHAR2(100),
    NOMBRE VARCHAR2(100),
    ID_PAIS NUMBER,
    ID_ESTADO NUMBER,
    ID_MUNICIPIO NUMBER,
    FORMACION ,
    ID_EON NUMBER,
    ID_ERA NUMBER,
    ID_EPOCA NUMBER, 
    COMENTARIOS VARCHAR2(500),
    USUARIO_ALTA NUMBER,
    USUARIO_MODIF NUMBER,
    CONSTRAINT FOSIL_PK PRIMARY KEY(ID_FOSIL),
    CONSTRAINT FOSI_PAIS_FK  FOREIGN KEY (ID_PAIS) REFERENCES FOSILES.PAISES (ID_PAIS),
    CONSTRAINT FOSI_ESTA_FK FOREIGN KEY (ID_ESTADO) REFERENCES FOSILES.ESTADOS (ID_ESTADO),
    CONSTRAINT FOSI_MUNI_FK FOREIGN KEY (ID_MUNICIPIO) REFERENCES FOSILES.MUNICIPIOS (ID_MUNICIPIO),
    CONSTRAINT FOSIL_EON_FK FOREIGN KEY (ID_EON) REFERENCES FOSILES.EONES (ID_EON),
    CONSTRAINT FOSIL_ERA_FK FOREIGN KEY (ID_ERA) REFERENCES FOSILES.ERAS (ID_ERA),
    CONSTRAINT FOSIL_EPOC_FK FOREIGN KEY (ID_EPOCA) REFERENCES FOSILES.EPOCAS (ID_EPOCA)
);
/
CREATE SEQUENCE fosiles_id
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
/
--ERAS GEOLOGICAS
CREATE TABLE FOSILES.EONES (
    ID_EON NUMBER,
    NOMBRE VARCHAR2(50)
);
/
CREATE TABLE FOSILES.ERAS (
    ID_EON NUMBER,
    ID_ERA NUMBER,
    NOMBRE VARCHAR2(50)
);
/
CREATE TABLE FOSILES.PERIODOS (
    ID_ERA NUMBER,
    ID_PERIODO NUMBER,
    NOMBRE VARCHAR2(50)
);
/
CREATE TABLE FOSILES.EPOCAS (
    ID_PERIODO NUMBER,
    ID_EPOCA NUMBER,
    NOMBRE VARCHAR2(50)
);
/
--LOCALIDADES
CREATE TABLE FOSILES.PAISES(
    ID_PAIS NUMBER,
    NOMBRE  VARCHAR2(100),
    CONSTRAINT PAIS_PK PRIMARY KEY(ID_PAIS)
);
/
CREATE SEQUENCE pais_id
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
/
CREATE TABLE FOSILES.ESTADOS(
    ID_ESTADO NUMBER,
    ID_PAIS NUMBER,
    NOMBRE VARCHAR2(300),
    CONSTRAINT ESTADO_PK PRIMARY KEY(ID_ESTADO, ID_PAIS),
    CONSTRAINT ESTA_PAIS_FK FOREIGN KEY (ID_PAIS) REFERENCES FOSILES.PAISES (ID_PAIS)
);
/
CREATE TABLE FOSILES.MUNICIPIOS (
    ID_MUNICIPIO NUMBER,
    ID_ESTADO NUMBER,
    ID_PAIS NUMBER,
    NOMBRE VARCHAR2(300),   
    CONSTRAINT MUNICIPIO_PK PRIMARY KEY(ID_MUNICIPIO, ID_ESTADO, ID_PAIS),
    CONSTRAINT MUNI_ESTA_FK FOREIGN KEY (ID_ESTADO, ID_PAIS) REFERENCES FOSILES.ESTADOS (ID_ESTADO, ID_PAIS)
);
/
--seguridad
CREATE TABLE usuarios (
  id_usuario NUMBER NOT NULL,
  usuario VARCHAR2(30) NOT NULL,
  credencial VARCHAR2(40) NOT NULL,
  activo NUMBER NOT NULL,
  usuario_root NUMBER,
  CONSTRAINT usuario_pk PRIMARY KEY (id_usuario),
  CONSTRAINT usuario_uk UNIQUE (usuario)
);
/
CREATE SEQUENCE usuario_id
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;


