DROP TABLE EPOCAS; --
DROP TABLE PERIODOS; --
DROP TABLE ERAS; --
DROP TABLE EONES; --
DROP TABLE MUNICIPIOS; --
DROP TABLE ESTADOS; --
DROP TABLE PAISES;--
DROP TABLE USUARIOS; --
DROP TABLE FOSILES; --
DROP SEQUENCE fosiles_id; --
DROP SEQUENCE eon_id; --
DROP SEQUENCE era_id; --
DROP SEQUENCE periodo_id; --
DROP SEQUENCE epoca_id; --
DROP SEQUENCE pais_id; --
DROP SEQUENCE usuario_id; --